[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#101C2E"
textColor = "#EAF2FF"
font = "sans serif"

[client]
showSidebarNavigation = false
toolbarMode = "developer"

[server]
runOnSave = true